language: r

notifications:
  email:
    on_success: change
    on_failure: change

git:
  depth: 3

dist: trusty

r:
  - release

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual
    - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

addons:
  apt:
    packages:
      - mecab
      - libmecab-dev
      - mecab-ipadic-utf8
      - libxml2-dev

warnings_are_errors: true

before_install:
  - wget "https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7QVR6VXJ5dWExSTQ" -O CRF++-0.58.tar.gz
  - tar -zxvf CRF++-0.58.tar.gz CRF++-0.58/
  - cd CRF++-0.58/
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ../
  - curl -sc /tmp/cookie "https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7SDd1Q1dUQkZQaUU" > /dev/null
  - CODE="$(awk '/_warning_/ {print $NF}' /tmp/cookie)"  
  - curl -Lb /tmp/cookie "https://drive.google.com/uc?export=download&confirm=${CODE}&id=0B4y35FiV1wh7SDd1Q1dUQkZQaUU" -o cabocha-0.69.tar.bz2
  - tar -jxvf cabocha-0.69.tar.bz2 cabocha-0.69/
  - cd cabocha-0.69/
  - ./configure --with-mecab-config=`which mecab-config` --with-charset=UTF8
  - make
  - make check
  - sudo make install
  - sudo ldconfig
  - cd ../

install:
  - R -e "0" --args --bootstrap-packrat
  - R -e "packrat::restore(restart = FALSE)"

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true
