# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Parse XML output of CaboCha
#' @param path String scalar.
#' @return data.frame.
#' @keywords internal
parse_xml <- function(path) {
    .Call(`_pipian_parse_xml`, path)
}

